describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})

//Place Order through storefront
  // cy.memberLogin(this.data.userName, this.data.password )
// cy.purchaseMembership()
// cy.placeOrderByCheque()
// cy.ErpUserLogin(this.data.adminUserName,this.data.adminPassword)
// cy.ConfirmPayment()
// cy.ErpUserLogin(this.data.FinanceUserName,this.data.FinancePassword)
// cy.ConfirmPayment() 
// cy.visit(mainDomainUrl) 
        // SfLandingPage.getLoginBtn().click()
        // SfLandingPage.getAcceptCookiesBtn().click()
        // SfLoginPage.getUserName().type(this.data.userName)
        // SfLoginPage.getPassword().type(this.data.password)
        // SfLoginPage.getLoginBtn().click()
        // SfAccountPage.getMTOrderType().click()
        // SfExtraCardPage.getAddMoreCardsBtn().click()
        // SfExtraCardPage.getTierLevelPopup().click()
        // SfExtraCardPage.getSelectTierLevel().click()
        // SfExtraCardPage.getNumberOfTierField().type('1')
        // SfExtraCardPage.getAgreementCheckBox().click()
        // SfExtraCardPage.getNextBtn().click()
        // SfCheckOutPage.getAgreeDisclaimerCheckBox().check()
        // SfCheckOutPage.getAgreeDisclaimerBtn().click()
        // SfCheckOutPage.getPayByChequeBtn().click()
        // SfCheckOutPage.getPlaceOrderBtn().click()
        // SfCheckOutPage.getOrderNumber().then(function(getOrderNumber){
        //     orderNumber = getOrderNumber.text()
        //     cy.task('setOrderNumber', orderNumber)
        //     cy.log("Order Number:" + orderNumber )
        //     })
        //cy.visit(ErpUrl)
        // cy.task('getErpUrl').then((ErpUrl) => {
        //     cy.visit(ErpUrl)        
        // })        
        // ErpLoginPage.getUserName().type(this.data.adminUserName)
        // ErpLoginPage.getPassword().type(this.data.adminPassword) 
        // ErpLoginPage.getLoginBtn().click()
        // ErpTransactionPage.getTransactionList().click()
        // cy.task('getOrderNumber').then((orderNumber) => {
        //     ErpTransactionPage.getOrderIdField().type(orderNumber)
        //     cy.log("Erp Order Number:"+ orderNumber)
        // })
        // ErpTransactionPage.getSearchBtn().click()
        // cy.wait(2000)
        // ErpTransactionPage.getViewBtn().click()
        // ErpOrderDetailsPage.getConfirmPaymentBtn().click()
        // ErpOrderDetailsPage.getAgreeConfirmBtn().click()
        // ErpMembersPage.getExitBtn().click()    
        // ErpLoginPage.getUserName().type(this.data.FinanceUserName)
        // ErpLoginPage.getPassword().type(this.data.FinancePassword) 
        // ErpLoginPage.getLoginBtn().click()
        // ErpTransactionPage.getTransactionList().click()
        // cy.task('getOrderNumber').then((orderNumber) => {
        //     ErpTransactionPage.getOrderIdField().type(orderNumber)
        //     cy.log("Erp Order Number:"+ orderNumber)
        // })
        // ErpTransactionPage.getSearchBtn().click()
        // cy.wait(2000)
        // ErpTransactionPage.getViewBtn().click()
        // ErpOrderDetailsPage.getConfirmPaymentBtn().click()
        // ErpOrderDetailsPage.getAgreeConfirmBtn().click()
        // ErpMembersPage.getExitBtn().click()       
